create extension if not exists pgcrypto;

do $$ begin
  create type public.user_role as enum ('CUSTOMER', 'ADMIN');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.ticket_status as enum ('VALID', 'USED', 'EXPIRED', 'DISABLED');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key,
  full_name text not null,
  phone text,
  email text not null unique,
  role public.user_role not null default 'CUSTOMER',
  created_at timestamptz not null default now()
);
create table if not exists public.ticket_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  price numeric(12,2) not null check (price >= 0),
  description text,
  active boolean not null default true
);
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles(id),
  amount numeric(12,2) not null check (amount >= 0),
  status text not null,
  reference text not null unique,
  paid_at timestamptz not null default now()
);
create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  code text not null unique,
  qr_token text not null unique,
  customer_id uuid not null references public.profiles(id),
  ticket_type_id bigint not null references public.ticket_types(id),
  payment_id bigint not null references public.payments(id),
  price numeric(12,2) not null,
  status public.ticket_status not null default 'VALID',
  purchased_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create table if not exists public.ticket_scans (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id),
  scanned_by_id uuid references public.profiles(id),
  scanned_at timestamptz not null default now(),
  result text not null
);
create index if not exists tickets_status_idx on public.tickets(status);
create index if not exists tickets_purchased_idx on public.tickets(purchased_at desc);

insert into public.ticket_types(name, price, description) values
  ('Standard', 5000, 'Accès à l’événement'), ('VIP', 15000, 'Accès prioritaire et espace VIP')
on conflict (name) do nothing;

alter table public.profiles enable row level security;
alter table public.ticket_types enable row level security;
alter table public.payments enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_scans enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'ADMIN');
$$;
create policy "admins can manage tickets" on public.tickets for all using (public.is_admin()) with check (public.is_admin());
create policy "admins can read profiles" on public.profiles for select using (public.is_admin() or id = auth.uid());
create policy "public can read active ticket types" on public.ticket_types for select using (active = true);

create or replace function public.create_purchase(p_full_name text, p_phone text, p_email text, p_quantity integer)
returns setof public.tickets language plpgsql security definer set search_path = public as $$
declare customer_id uuid; type_row public.ticket_types%rowtype; payment_id bigint;
begin
  if p_quantity < 1 or p_quantity > 10 then raise exception 'Quantité invalide'; end if;
  select id into customer_id from profiles where lower(email) = lower(p_email);
  if customer_id is null then
    customer_id := gen_random_uuid();
    insert into profiles(id, full_name, phone, email, role) values (customer_id, p_full_name, p_phone, lower(p_email), 'CUSTOMER');
  else update profiles set full_name = p_full_name, phone = p_phone where id = customer_id;
  end if;
  select * into type_row from ticket_types where active = true order by id limit 1;
  if type_row.id is null then raise exception 'Aucun type de ticket actif'; end if;
  insert into payments(customer_id, amount, status, reference) values (customer_id, type_row.price * p_quantity, 'PAID', 'PAY-' || gen_random_uuid()) returning id into payment_id;
  return query insert into tickets(code, qr_token, customer_id, ticket_type_id, payment_id, price, expires_at)
    select 'TKT-' || upper(substr(encode(gen_random_bytes(9), 'hex'), 1, 12)), upper(encode(gen_random_bytes(24), 'hex')), customer_id, type_row.id, payment_id, type_row.price, now() + interval '1 month'
    from generate_series(1, p_quantity) returning *;
end $$;

create or replace function public.verify_ticket(p_code text) returns setof public.tickets
language plpgsql security definer set search_path = public as $$
declare t public.tickets%rowtype; result text;
begin
  select * into t from tickets where code = p_code for update;
  if t.id is null then raise exception 'Ticket introuvable'; end if;
  if t.status = 'VALID' and now() > t.expires_at then t.status := 'EXPIRED'; end if;
  result := case when t.status = 'VALID' then 'VALID' else t.status::text end;
  if t.status = 'VALID' then update tickets set status = 'USED' where id = t.id returning * into t; end if;
  insert into ticket_scans(ticket_id, scanned_by_id, result) values (t.id, auth.uid(), result);
  return next t;
end $$;

create or replace function public.dashboard_stats() returns json language sql security definer set search_path = public as $$
  select json_build_object('sold', (select count(*) from tickets), 'valid', (select count(*) from tickets where status='VALID'), 'used', (select count(*) from tickets where status='USED'), 'expired', (select count(*) from tickets where status='EXPIRED'), 'revenue', coalesce((select sum(amount) from payments where status='PAID'), 0));
$$;
